# Usa a imagem oficial do Nginx
FROM nginx:alpine

# Remove a página padrão
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos do site para o diretório padrão do Nginx
COPY site/ /usr/share/nginx/html/

# (Opcional) Copia a config personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
